### ISSUE TITLE
marvin model archive corrupted/wrong format

### ISSUE THREAD

**Issue by poohsen** [MycroftAI/Precise-Community-Data#16]
**Describe the bug**
Neither unzip, nor gunzip nor tar -xaf know how to open that file.

**To Reproduce**
1. gunzip marvin-en-0.3.0-20190817-jarbas.tar.gz - BOOM

**Expected behavior**
Access to the model files after unzipping.

**Log files**
gunzip: marvin-en-0.3.0-20190817-jarbas.tar.gz: not in gzip format

**Environment (please complete the following information):**
 - OSX 11.2.3
 - Ubuntu 20

**Comment by forslund** [comment]
Tried it just now and it works here:

```
$ tar -xvf marvin-en-0.3.0-20190817-jarbas.tar.gz 
marvin.pb
marvin.pb.params
```

Try to redownload (I used the following link in the browser: https://github.com/MycroftAI/Precise-Community-Data/raw/master/marvin/models/marvin-en-0.3.0-20190817-jarbas.tar.gz)

**Comment by poohsen** [comment]
you're right, this works. And I know now what happened: I navigated to the tar.gz file in the UI, then right-clicked on it and selected "copy link location" thinking this would get me the archive. Instead it's HTML...
Thanks for looking into this for me @forslund !
